version: "3.1"
services:
  www:
    build: docker
    environment:
      - APACHE_RUN_USER=agility
      - APACHE_RUN_GROUP=agility
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - ${PORT:-443}:443
    volumes:
      - ./agility:/var/www/html/agility:z
      - ${CONFIG_DIR:-./config}:/var/www/html/config:z
      - ${LOGS_DIR:-./logs}:/var/www/html/logs:z
    links:
      - db
    networks:
      - default
  db:
    image: mariadb:10.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./extras/bare_bones.sql:/docker-entrypoint-initdb.d/bare_bones.sql:z
      - ./extras/mysql.cnf:/etc/mysql/conf.d/my.cnf:z
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - ${ADMIN_PORT:-8000}:80
volumes:
  persistent:
